---
version: '3'

services:

  geoipupdate:
    image: maxmindinc/geoipupdate
    container_name: geoipupdate
    environment:
      TZ: Europe/Berlin
      GEOIPUPDATE_ACCOUNT_ID: my-account-id
      GEOIPUPDATE_LICENSE_KEY: my-license-key
      GEOIPUPDATE_EDITION_IDS: GeoLite2-Country GeoLite2-ASN GeoLite2-City
      GEOIPUPDATE_FREQUENCY: 48
      GEOIPUPDATE_VERBOSE: 'true'
    volumes:
      - '.:/usr/share/GeoIP'
