name: Go

on:
  push:
    branches: [ $default-branch ]
    paths-ignore:
      - '**.md'
  pull_request:
    branches: [ $default-branch ]
    paths-ignore:
      - '**.md'
jobs:

  build:
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        operating-system: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Build
        run: go version
